name: Publish gem to Nexus
description: Build and publish a ruby gem to a Sonatype's Nexus Repository
author: Drowze
branding:
  icon: upload-cloud
  color: red
inputs:
  url:
    description: Nexus repository URL
    required: true
  username:
    description: Username with write access to Nexus
    required: true
  password:
    description: Password to Nexus
    required: true
outputs:
  name:
    description: Gem name (as described on the gemspec)
  full-version:
    description: Gem version that was published (as described on the gemspec). Only present if upload was successful.
runs:
  using: docker
  post-if: always()
  image: Dockerfile
  args:
    - ${{ inputs.url }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
